### ISSUE TITLE
feat: Ticket System

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Bots/Project-Jelly#1]
Should handle a ticket system as well! :D

**Comment by EnigmaOneOfficial** [comment]
I will add this to the list. I'll also update Jelly README to include this and get rid of profile system, as we should have Reppy handle that.

**Comment by TinyPandas** [comment]
I'm gonna implement the usage in TheGate, and have Reppy pull the data from the DB as they will be sharing data.
